import json

data = {
    "ゴシック体の活字": {"example": "タイトルには太いゴシック体の活字を使用してください。", "meaning": "Hãy sử dụng chữ kiểu in đậm (chữ Gothic) cho tiêu đề."},
    "ロゴ": {"example": "新製品のために新しいロゴをデザインした。", "meaning": "Tôi đã thiết kế một logo mới cho sản phẩm mới."},
    "書体": {"example": "公式文書には明朝の書体を使用するのが一般的だ。", "meaning": "Sử dụng phông chữ Mincho cho các tài liệu chính thức là điều phổ biến."},
    "板": {"example": "オフィスの入り口に案内の板を取り付ける。", "meaning": "Lắp một tấm bảng hướng dẫn ở lối vào văn phòng."},
    "看板": {"example": "新しい店舗の看板が完成しました。", "meaning": "Bảng hiệu của cửa hàng mới đã hoàn thành."},
    "この時勢": {"example": "この時勢において、コスト削減は不可欠です。", "meaning": "Tại thời điểm này, việc cắt giảm chi phí là không thể thiếu."},
    "単刀直入": {"example": "単刀直入に申し上げますが、この契約は破棄させてください。", "meaning": "Nói thẳng ra là, xin hãy cho phép chúng tôi hủy hợp đồng này."},
    "そうするとこの場で決められる。": {"example": "条件が合えば、そうするとこの場で決められる。", "meaning": "Nếu các điều kiện phù hợp, nếu được thì có thể chốt ngay bây giờ."},
    "考えらないこともない": {"example": "納期を延ばしていただければ、考えらないこともないです。", "meaning": "Nếu kéo dài thời hạn giao hàng, chúng tôi cũng có thể cân nhắc."},
    "ネックになる": {"example": "資金不足がプロジェクト推進の際ネックになる。", "meaning": "Thiếu vốn sẽ trở thành khó khăn (nút thắt) khi thúc đẩy dự án."},
    "単価": {"example": "大量に発注していただくことで、単価を下げることができます。", "meaning": "Bằng cách đặt hàng số lượng lớn, chúng tôi có thể giảm đơn giá."},
    "キーパーソン": {"example": "この交渉をまとめるためには、彼がキーパーソンとなる。", "meaning": "Để chốt được cuộc đàm phán này, anh ấy sẽ là nhân vật chủ chốt."},
    "要": {"example": "顧客との信頼関係がビジネスの要です。", "meaning": "Mối quan hệ tin cậy với khách hàng là điểm cốt yếu của business."},
    "経営の要": {"example": "人材育成こそが、今後の経営の要となる。", "meaning": "Đào tạo nhân tài chính là điểm trọng yếu của quản lý kinh doanh sau này."},
    "保養所": {"example": "週末は会社の保養所でリフレッシュしました。", "meaning": "Cuối tuần tôi đã nghỉ ngơi thư giãn tại khu nghỉ dưỡng của công ty."},
    "おたく": {"example": "おたくの製品は非常に品質が良いと評判です。", "meaning": "Sản phẩm của công ty (quý vị) được đánh giá rất cao về chất lượng."},
    "フル稼働": {"example": "年末の需要に合わせ、工場は24時間フル稼働している。", "meaning": "Để đáp ứng nhu cầu cuối năm, nhà máy đang hoạt động hết công suất suốt 24 giờ."},
    "ご猶予をいただけないかと": {"example": "支払いの件ですが、少しご猶予をいただけないかと思いまして。", "meaning": "Về việc thanh toán, chúng tôi hy vọng quý vị có thể cho chúng tôi thêm chút thời gian."},
    "支障をきたす": {"example": "システムの不具合が業務に支障をきたしている。", "meaning": "Lỗi hệ thống đang gây trở ngại (ảnh hưởng) đến công việc."},
    "売掛金": {"example": "今月末までに売掛金の回収を終わらせる必要がある。", "meaning": "Cần phải hoàn tất việc thu hồi các khoản phải thu trước cuối tháng này."},
    "途中採用": {"example": "即戦力を求めるため、途中採用を積極的に行っている。", "meaning": "Để có nguồn nhân lực dùng được ngay, chúng tôi đang tích cực tuyển dụng giữa chừng."},
    "利回り": {"example": "この商品は高い利回りが期待できる投資案件だ。", "meaning": "Sản phẩm này là dự án đầu tư được kỳ vọng sẽ mang lại tỷ suất sinh lời cao."},
    "利率": {"example": "銀行の貸出利率が下がったため、資金を借り入れやすくなった。", "meaning": "Vì lãi suất cho vay của ngân hàng đã giảm nên việc vay vốn trở nên dễ dàng hơn."},
    "単身赴任": {"example": "来月から大阪支社へ単身赴任することになりました。", "meaning": "Từ tháng sau, tôi sẽ đi công tác một mình đến chi nhánh Osaka."},
    "シニア": {"example": "シニア層に向けた新しいサービスを企画する。", "meaning": "Lên kế hoạch một dịch vụ mới hướng tới tầng lớp người cao tuổi."},
    "ジュニア": {"example": "ジュニアアシスタントとしてチームに参加した。", "meaning": "Tham gia vào nhóm với tư cách trơ lý cấp thấp (người mới/ít kn)."},
    "ワンパック": {"example": "サービスが全てワンパックになっている商品です。", "meaning": "Đây là sản phẩm mà mọi dịch vụ được gói gọn trong một."},
    "飛び回る": {"example": "営業担当として、全国の支社を飛び回っている。", "meaning": "Với tư cách là người phụ trách bán hàng, tôi đang bay tới (chạy ngược xuôi) các chi nhánh trên toàn quốc."},
    "健康食品": {"example": "最近、中高年向けに健康食品の売れ行きが良い。", "meaning": "Gần đây, thực phẩm tốt cho sức khỏe bán rất chạy cho đối tượng trung niên và cao tuổi."},
    "オーダーメイド": {"example": "お客様のご要望に合わせてオーダーメイドの家具を作る。", "meaning": "Chúng tôi làm ra những đồ nội thất được làm theo đơn đặt hàng tùy vào yêu cầu của khách hàng."},
    "ラインアップ": {"example": "今年の製品ラインアップは、エコを重視したものが多い。", "meaning": "Dòng (lineup) sản phẩm của năm nay chủ yếu chú trọng vào yếu tố thân thiện với môi trường."},
    "少し先": {"example": "少し先のことにはなりますが、新プロジェクトの準備を始めます。", "meaning": "Dù đó là chuyện của một tương lai gần, nhưng chúng ta sẽ bắt đầu chuẩn bị dự án mới."},
    "中間計算": {"example": "プロジェクトの中間計算を行い、予算の進捗を確認した。", "meaning": "Đã tiến hành tính toán giữa kỳ cho dự án và kiểm tra tiến độ của ngân sách."},
    "団塊世代": {"example": "団塊世代の退職により、人材不足が懸念されている。", "meaning": "Do sự nghỉ hưu của thế hệ baby boomers (hậu chiến tranh), tình trạng thiếu nhân lực đang đáng lo ngại."},
    "取り寄せる": {"example": "本社から必要な資料を取り寄せる。", "meaning": "Xin gửi / yêu cầu trụ sở chính gửi lại tài liệu cần thiết."},
    "取り返す": {"example": "先月の遅れを、今月で取り返すつもりです。", "meaning": "Tôi dự định tháng này sẽ bù đắp (đòi lại/gỡ lại) cho sự chậm trễ của tháng trước."},
    "送付状": {"example": "書類を郵送する際は、必ず送付状を添付してください。", "meaning": "Khi gửi tài liệu qua đường bưu điện, nhất định phải đính kèm thư xin gửi (thư đính kèm)."},
    "下げ幅": {"example": "株価の下げ幅が大きく、市場は混乱している。", "meaning": "Biên độ giảm giá cổ phiếu lớn, thị trường đang hỗn loạn."},
    "初稿": {"example": "デザインの初稿が上がってきましたので、ご確認ください。", "meaning": "Bản thảo đầu tiên của thiết kế đã lên, xin vui lòng kiểm tra."},
    "クエスチョンマーク": {"example": "彼のその発言にはクエスチョンマークがつく。", "meaning": "Có một dấu hỏi (vấn đề nghi ngờ) trong phát ngôn của anh ấy."},
    "持ち越す": {"example": "本日の会議で決まらなかった議題は、次回へ持ち越す。", "meaning": "Các chủ đề chưa được quyết định trong cuộc họp hôm nay sẽ được bảo lưu sang lần tiếp theo."},
    "切り上げる": {"example": "今日は早めに仕事を切り上げて、飲みに行こう。", "meaning": "Hôm nay hãy kết thúc công việc sớm và đi uống nào."},
    "前倒す": {"example": "スケジュールの進行状況が良いので、計画を前倒すことにした。", "meaning": "Tiến độ của lịch trình rất tốt nên chúng tôi quyết định đẩy nhanh kế hoạch đi làm trước."},
    "位置付け": {"example": "この製品の市場での位置付けを再考する必要がある。", "meaning": "Cần phải xem xét lại vị thế (định vị) của sản phẩm này trên thị trường."},
    "商品の位置付け": {"example": "若者向けの商品の位置付けを明確にする。", "meaning": "Làm rõ định vị của sản phẩm nhắm tới khách hàng trẻ tuổi."},
    "待ったが掛かる": {"example": "プロジェクトの進行に関して、上層部から待ったが掛かった。", "meaning": "Có chuyện đình chỉ (bảo chờ) từ phía ban lãnh đạo cấp cao liên quan đến tiến độ thực hiện dự án."},
    "発信元": {"example": "このEメールの発信元を確認してください。", "meaning": "Vui lòng xác nhận người vởi của email này."},
    "納品書": {"example": "商品に納品書を同封してお送りします。", "meaning": "Tôi sẽ gửi kèm phiếu giao hàng (Invoice) cùng sản phẩm."},
    "売り込む": {"example": "当社の新しいサービスを積極的に売り込む。", "meaning": "Tích cực bán và tiếp thị (chào bán) dịch vụ mới của công ty chúng tôi."},
    "フェアに出る": {"example": "新事業の宣伝のために、大きなフェアに出ることにした。", "meaning": "Tôi quyết định tham gia hội chợ lớn để quảng bá cho mảng kinh doanh doanh mới."},
    "2の足を踏む": {"example": "リスクが大きいため、新しい事業への投資に2の足を踏んでいる。", "meaning": "Bởi rủi ro lớn, nên tôi đang do dự phân vân (ngần ngại) trước việc đầu tư vào mảng kd mới."},
    "手もあります": {"example": "リースではなく、一括購入するという手もあります。", "meaning": "Thay vì thuê, việc mua đứt đi cũng là một cách giải quyết (có cách như vậy)."},
    "知名度が低い": {"example": "そのスタートアップは、まだ知名度が低いため苦労している。", "meaning": "Công ty startup đó gặp khó khăn vì độ nhận diện thương hiệu vẫn còn thấp."},
    "足で稼ぐ": {"example": "優れた営業マンは、ネットに頼らず足で稼ぐ。", "meaning": "Một nhân viên sales xuất sắc sẽ kiếm sống (chạy tới các điểm) bằng đôi chân mình chứ không chỉ phụ thuộc Internet."},
    "小売店を回る": {"example": "新商品を紹介するため、自ら小売店を回る。", "meaning": "Tôi đã tự mình đi vòng quanh đến thăm các cửa tiệm bán lẻ để giới thiệu sản phẩm mới."},
    "自信作": {"example": "今回の商品は、わが社の技術を結集した自信作だ。", "meaning": "Sản phẩm lần này là thành tựu kiêu hãnh (tác phẩm tâm đắc) hội tụ công nghệ của công ty."},
    "相見積もりを取る": {"example": "コストを比較するため、3社に相見積もりを取る。", "meaning": "Tôi lấy báo giá tương đối từ 3 công ty để so sánh chi phí."},
    "５社候補を選ぶ": {"example": "コンペティションのために、予め５社候補を選ぶ。", "meaning": "Chọn sẵn 5 công ty ứng cử viên cho cuộc đấu thầu."},
    "粉骨砕身": {"example": "粉骨砕身して会社のために働く。", "meaning": "Làm việc tận tâm tận lực (hi sinh cái thân) vì công ty."},
    "好意": {"example": "取引先の好意に甘えて、納期を延ばしてもらった。", "meaning": "Dựa dẫm vào sự hảo ý (thiện ý) của bên đối tác, tôi đã được gia hạn thêm deadline."},
    "個別ミーティング": {"example": "各メンバーと個別ミーティングを行い、状況を把握する。", "meaning": "Tiến hành họp mặt cá nhân với từng nhân viên để nắm bắt tình hình."},
    "受注": {"example": "大型のシステム開発案件を受注した。", "meaning": "Chúng tôi đã nhận được một đơn đặt hàng phát triển hệ thống cỡ lớn."},
    "体裁": {"example": "企画書としての体裁を整えてから提出してください。", "meaning": "Vui lòng dọn dẹp (chỉnh sửa) lại ngoại hình / vẻ bề ngoài của bản kế hoạch rồi mới nộp."},
    "ポテンシャル": {"example": "新入社員たちは高いポテンシャルを秘めている。", "meaning": "Các nhân viên mới chứa đựng tiềm năng rất cao."},
    "打ち上げ": {"example": "プロジェクトが成功裏に終わり、みんなで打ち上げに行った。", "meaning": "Dự án kết thúc thành công tốt đẹp, mọi người đã đi uống party ra mắt (ăn mừng)."},
    "幹事をやる": {"example": "今年の忘年会の幹事をやることになった。", "meaning": "Tôi sẽ làm ban cán sự / người phụ trách tiệc liên hoan cuối năm nay."},
    "盛大にやる": {"example": "会社の創立記念パーティーを盛大にやる。", "meaning": "Chúng ta sẽ tổ chức tiệc kỷ niệm thành lập công ty hoành tráng."},
    "乾杯の音頭": {"example": "社長に乾杯の音頭をとっていただいた。", "meaning": "Giám đốc sẽ đảm nhận việc đọc diễn văn hô nâng ly cạn chén."},
    "顔をたてる": {"example": "取引先の社長の顔をたてるために、この条件をのむことにした。", "meaning": "Tôi sẽ chấp nhận điều khoản này để giữ thể diện cho giám đốc bên đối tác."},
    "立役者": {"example": "彼は今回の新規事業成功の立役者の一人だ。", "meaning": "Anh ấy là một trong những diễn viên trụ cột (người dẫn dắt thành công) của mảng kd khởi nghiệp đợt này."},
    "年功序列": {"example": "最近の企業は年功序列から成果主義へと移行しつつある。", "meaning": "Gần đây các doanh nghiệp dần chuyển từ chế độ xếp hạng sống lâu lên cố (thâm niên) sang chế độ đánh giá theo hiệu suất."},
    "騒動。騒音。": {"example": "工事の騒音で近隣から苦情が入り、対応に追われた。", "meaning": "Tiếng ồn công trường khiến hàng xóm than phiền, khiến chúng tôi chật vật ứng phó."},
    "気を引き締める": {"example": "大きなミスを起こさないよう、気を引き締めて業務に取り組む。", "meaning": "Tôi sẽ cố gắng làm việc hết sức cẩn thận, lên tinh thần để không phạm sai lầm lớn."},
    "回覧": {"example": "この資料を社内に回覧しておいてください。", "meaning": "Xin vui lòng chuyền tay lan truyền (luân chuyển) tài liệu này trong công ty."},
    "害虫駆除": {"example": "オフィスの衛生環境を保つため、害虫駆除業者を呼んだ。", "meaning": "Để giữ vệ sinh văn phòng, tôi đã gọi nhân viên diệt trừ côn trùng."},
    "こっちの島": {"example": "プロジェクトのメイン業務は、こっちの島（チーム）で担当します。", "meaning": "Mảng kinh doanh chính của dự án sẽ do đảo này (nhóm này) phụ trách."},
    "消費が冷え込む": {"example": "不景気の影響により、旅行関連の消費が冷え込んでいる。", "meaning": "Do ảnh hưởng từ suy thoái kinh tế, lượng chi tiêu trong du lịch ngày càng ảm đạm nguội lạnh."},
    "耐久性": {"example": "この製品は耐久性に優れているのが特徴だ。", "meaning": "Đặc trưng của sản phẩm này này độ bền vượt trội."}
}

with open('examples_csv.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("First batch of generated CSV examples saved.")
