import json
import os

with open('examples.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

new_data = {
    "コントラスト": {"example": "プレゼン資料は、色が強調されるようにコントラストをつける。", "meaning": "Tài liệu thuyết trình cần được điều chỉnh độ tương phản để làm nổi bật màu sắc."},
    "駆け込み購入": {"example": "消費税増税前に、家電の駆け込み購入が増えた。", "meaning": "Trước khi tăng thuế tiêu dùng, lượng mua hàng đổ xô (mua vội vàng) đồ gia dụng đã tăng."},
    "預貯金": {"example": "いざという時に備えて、一定の預貯金を持っておく。", "meaning": "Để đề phòng khi khẩn cấp, cần giữ một số tiền gửi tiết kiệm nhất định."},
    "カー用品": {"example": "週末は新しいカー用品を探しに自動車用品店へ行った。", "meaning": "Cuối tuần tôi đã đến cửa hàng phụ tùng ô tô để tìm mua các sản phẩm dành cho xe hơi."},
    "売上高": {"example": "新店舗のオープンにより、今月の売上高が目標を達成した。", "meaning": "Nhờ khai trương cửa hàng mới, doanh thu tháng này đã đạt mục tiêu."},
    "増減率": {"example": "先月比での顧客数の増減率を細かく分析する。", "meaning": "Tôi đang phân tích chi tiết tỷ lệ tăng giảm lượng khách hàng so với tháng trước."},
    "給湯マシン /きゅうとう~/": {"example": "オフィスの給湯マシンが故障し、修理業者が来た。", "meaning": "Máy đun nước nóng ở văn phòng bị hỏng nên nhân viên sửa chữa đã đến."},
    "先発 /せんぱつ/": {"example": "先発のグループが先に会議室へ向かいます。", "meaning": "Nhóm đi trước sẽ đến phòng họp trước."},
    "後発 /こうはつ/": {"example": "我々の製品は後発ですが、品質では負けません。", "meaning": "Sản phẩm của chúng ta đi sau (được tung ra sau), nhưng chất lượng không thua kém."},
    "直帰 /ちょっき/": {"example": "午後の営業が終わった後、そのまま直帰する予定です。", "meaning": "Sau khi kết thúc công việc kinh doanh buổi chiều, tôi định sẽ đi thẳng về nhà không quay lại công ty."},
    "時間帯": {"example": "この時間帯は道路が大変混雑しています。", "meaning": "Khung giờ này đường đang rất tắc nghẽn."},
    "すり合わせる": {"example": "両社のスケジュールをすり合わせるために連絡を取る。", "meaning": "Tôi sẽ liên lạc để điều chỉnh chắp nối lịch trình của hai công ty sao cho phù hợp."},
    "垂れ幕 /たれまく/": {"example": "イベント会場の外には大きな垂れ幕が掛かっていた。", "meaning": "Bên ngoài hội trường sự kiện có treo một tấm băng rôn cỡ lớn."},
    "広報部": {"example": "新製品の記者会見は広報部が担当します。", "meaning": "Phòng quan hệ công chúng (PR) chịu trách nhiệm tổ chức họp báo về sản phẩm mới."},
    "優待": {"example": "お得意様には、特別な割引優待をご案内いたします。", "meaning": "Chúng tôi dành chế độ ưu đãi giảm giá đặc biệt cho những khách hàng thân thiết."},
    "技能教習": {"example": "自動車学校で最初の技能教習を受けた。", "meaning": "Tôi đã học khóa huấn luyện thực hành kỹ năng đầu tiên ở trường dạy lái xe."},
    "控え": {"example": "申請書類の提出後は、こちらの控えを大切に保管してください。", "meaning": "Sau khi nộp hồ sơ xin việc, vui lòng giữ kỹ bản sao dự phòng (bản giữ lại)."},
    "損益計算書": {"example": "決算時に、損益計算書の詳しい内容を株主に説明した。", "meaning": "Trong kỳ quyết toán, báo cáo lời lỗ đã được giải thích chi tiết cho các cổ đông."},
    "営業利益": {"example": "コスト削減の成果として、今月の営業利益が向上した。", "meaning": "Nhờ kết quả của việc cắt giảm ngân sách, lợi nhuận hoạt động kinh doanh (lãi ròng) tháng này đã tăng."},
    "営業外損益": {"example": "為替差損により営業外損益が発生しており、最終利益に影響した。", "meaning": "Do lỗ tỉ giá nên phát sinh lỗ/lãi ngoài hoạt động kinh doanh, làm ảnh hưởng đến lợi nhuận ròng cuối cùng."},
    "経常利益": {"example": "今年の経常利益は大幅に目標を上回った。", "meaning": "Lợi nhuận thường xuyên năm nay đã vượt xa mục tiêu."},
    "儲かる/もうかる/": {"example": "あのビジネスは非常に儲かるという話だ。", "meaning": "Người ta nói rằng dự án kinh doanh đó đang sinh lời (kiếm được tiền) rất tốt."},
    "受講料": {"example": "ビジネスセミナーの受講料は来週までに振り込んでください。", "meaning": "Học phí của khóa hội thảo kinh doanh, xin vui lòng chuyển khoản trước tuần sau."},
    "税抜": {"example": "見積書には税抜の価格で記載しております。", "meaning": "Trong bảng báo giá, giá được tính trước khi có thuế (chưa bao gồm thuế)."},
    "税込み": {"example": "税込みの総支払額をご確認いただけますか。", "meaning": "Bạn có thể kiểm tra tổng số tiền thanh toán đã bao gồm thuế không?"},
    "建て売り": {"example": "新婚の際に、郊外の建て売り住宅を購入した。", "meaning": "Khi mới cưới, tôi đã mua một căn nhà xây sẵn bán ở ngoại ô."},
    "単身赴任": {"example": "大阪支社へ単身赴任することになりました。", "meaning": "Tôi sẽ đi chuyển công tác một mình (không đưa gia đình theo) đến chi nhánh Osaka."},
    "個人事業主": {"example": "独立して個人事業主として活動を始める。", "meaning": "Tôi bắt đầu hoạt động với tư cách là người kinh doanh tự do (chủ hộ kinh doanh gia đình)."},
    "官公庁": {"example": "我が社は、官公庁が入札する案件を多数受注している。", "meaning": "Công ty chúng tôi nhận được rất nhiều dự án do cơ quan chính phủ đấu thầu."},
    "買取": {"example": "使わなくなった機材を業者に買取ってもらった。", "meaning": "Chúng tôi nhờ nhà thầu mua lại các thiết bị không còn sử dụng."},
    "売却 /ばいきゃく/": {"example": "不要な資産を売却し、会社のキャッシュフローを改善する。", "meaning": "Bán đi tài sản không cần thiết để cải thiện dòng tiền của công ty."},
    "処分": {"example": "不要なファイルを早めに処分してください。", "meaning": "Vui lòng vứt bỏ đi các tài liệu không cần thiết sớm."},
    "試乗": {"example": "新車を購入する前に、一度試乗して確認した。", "meaning": "Trước khi mua chiếc xe mới, tôi đã lái thử để kiểm tra."},
    "早番 /はやばん/": {"example": "明日は早番のシフトなので、早く帰宅します。", "meaning": "Ngày mai là ca làm việc buổi sáng nên tôi sẽ về sớm."},
    "遅番 /おそばん/": {"example": "今週は遅番が続くため、朝の時間がゆっくりできる。", "meaning": "Tuần này tôi làm ca muộn liên tục nên có thời gian thong thả vào buổi sáng."},
    "業務拡大": {"example": "当面の業務拡大に向けて、新しい人材を募集している。", "meaning": "Chúng tôi đang tuyển dụng nhân sự mới để mở rộng kinh doanh trong thời gian tới."},
    "完備": {"example": "このマンションは最新のセキュリティシステムが完備されています。", "meaning": "Khu chung cư này được trang bị hoàn chỉnh (đầy đủ tiện nghi) hệ thống an ninh mới nhất."},
    "ぽかぽか": {"example": "春らしいぽかぽかした陽気になってきた。", "meaning": "Thời tiết cũng bắt đầu ấm áp dần lên như mùa xuân."},
    "参考書": {"example": "BJT試験の準備のため、役に立ちそうな参考書を買った。", "meaning": "Tôi đã mua một cuốn sách tham khảo hữu ích để chuẩn bị cho kỳ thi BJT."},
    "お気に召さない /おきにめさない/": {"example": "デザインがお気に召さない場合は、再度ご提案いたします。", "meaning": "Nếu quý khách không vừa ý (không thích) thiết kế, chúng tôi sẽ đề xuất lại."},
    "特記事項": {"example": "契約書には必ず特記事項の欄もご確認ください。", "meaning": "Nhất định phải kiểm tra cột các điều khoản đặc biệt (ghi chú đặc biệt) trong hợp đồng."},
    "返送": {"example": "署名捺印済みの書類を速やかにご返送ください。", "meaning": "Vui lòng gửi trả lại văn bản đã có chữ ký, đóng dấu ngay lập tức."},
    "取扱い説明書": {"example": "操作の前に、同封の取扱い説明書をお読みください。", "meaning": "Trước khi sử dụng, vui lòng đọc sách hướng dẫn đi kèm."},
    "同封物": {"example": "パッケージを開き、同封物に不足がないか確認した。", "meaning": "Sau khi mở gói hàng, tôi kiểm tra xem có thứ đi kèm gửi theo nào bị thiếu không."},
    "本音を洩らす": {"example": "彼は飲み会の席で、会社に対する本音を洩らした。", "meaning": "Anh ấy đã để lộ suy nghĩ thật lòng (thú tâm thật ngôn) về công ty tại bàn rượu."},
    "代引き": {"example": "お支払いはクレジットカードの他に、代引きもご利用可能です。", "meaning": "Ngoài thẻ tín dụng, bạn cũng có thể thanh toán bằng cách trả tiền khi nhận hàng (COD)."},
    "足取り /あしどり/": {"example": "商談が成功し、帰り道は足取りがとても軽かった。", "meaning": "Vì buổi thương thảo thành công, bước chân trên đường về rất nhẹ nhàng."},
    "当面": {"example": "当面の間は、リモートワークでの対応となります。", "meaning": "Trong thời gian trước mắt (hiện tại), chúng tôi sẽ làm việc từ xa."},
    "見当たらない": {"example": "必要な資料がオフィスのどこにも見当たらない。", "meaning": "Tôi không thể tìm thấy tài liệu cần thiết ở đâu trong văn phòng."},
    "利回り": {"example": "この商品は高い利回りが魅力的な投資案件です。", "meaning": "Sản phẩm này là một dự án đầu tư hấp dẫn với tỷ suất sinh lợi (lãi gộp) cao."},
    "為替相場": {"example": "最近の為替相場の急激な変動には注意が必要だ。", "meaning": "Cần chú ý tới những biến động đột ngột của tỷ giá hối đoái gần đây."},
    "同行": {"example": "顧客訪問の際、新入社員も同行させて経験を積ませる。", "meaning": "Trong khi đến thăm khách hàng, các nhân viên mới cũng được phép đi cùng (đồng hành) để tích lũy kinh nghiệm."},
    "日頃": {"example": "日頃のご愛顧に、心より感謝申し上げます。", "meaning": "Chúng tôi gửi lời cảm ơn từ tận đáy lòng về sự ủng hộ thường xuyên (hàng ngày) của quý khách."},
    "ご愛顧賜りますよう": {"example": "今後とも変わらぬご愛顧賜りますようお願い申し上げます。", "meaning": "Rất mong sau này vẫn sẽ tiếp tục nhận được sự yêu thương ủng hộ (mong quý khách nâng đỡ) như trước."},
    "車線閉鎖": {"example": "工事のため、高速道路の一部で車線閉鎖が行われている。", "meaning": "Do thi công, một đoạn đường cao tốc bị đóng làn đường."},
    "避難訓練": {"example": "地震を想定して、全社員参加の避難訓練を実施した。", "meaning": "Đã tiến hành diễn tập sơ tán giả định động đất với sự tham gia của tất cả nhân viên."},
    "一斉 ＝ ~同時に": {"example": "合図と同時に、一斉に作業を開始してください。", "meaning": "Khi có tín hiệu, hãy bắt đầu công việc đồng loạt cùng một lúc."},
    "非常階段": {"example": "火災時にはエレベーターを使用せず、非常階段を使ってください。", "meaning": "Trường hợp có cháy không được dùng thang máy, hãy sử dụng cầu thang thoát hiểm."},
    "退避": {"example": "危険が迫っているため、安全な場所へすぐに退避してください。", "meaning": "Vì nguy hiểm đang đến gần, vui lòng sơ tán ngay đến nơi an toàn."},
    "点呼": {"example": "出発前に、全員が揃っているか点呼を取ります。", "meaning": "Trước khi khởi hành, tôi sẽ điểm danh xác nhận mọi người có mặt đầy đủ chưa."},
    "所定": {"example": "提出書類には、所定の書式をご使用ください。", "meaning": "Vui lòng sử dụng biểu mẫu quy định chuẩn cho tài liệu nộp."},
    "中途採用": {"example": "経験豊富な人材を確保するため、中途採用を増やしている。", "meaning": "Để thu hút nhân lực giàu kinh nghiệm, chúng tôi đang tăng cường tuyển dụng giữa chừng (những người đã đi làm)."},
    "....と認識でいいですか？": {"example": "来週の打ち合わせは金曜日で確定、という認識でいいですか？", "meaning": "Tôi hiểu (có nhận thức) là cuộc họp tuần sau diễn ra chốt vào thứ Sáu có đúng không ạ?"},
    "第一歩": {"example": "新市場への進出は、会社の国際化の第一歩です。", "meaning": "Việc xâm nhập vào thị trường mới là bước đi đầu tiên trong quá trình quốc tế hóa của công ty."},
    "口先よりも実践が大事": {"example": "いくら良いアイデアがあっても、口先よりも実践が大事だ。", "meaning": "Dù ý tưởng có hay đến đâu, thực hành vẫn quan trọng hơn lời nói suông (nói mồm)."},
    "売掛金": {"example": "今月末に振り込まれる売掛金の残高を確認する。", "meaning": "Kiểm tra số dư tiền phải thu (bán nợ) sẽ được chuyển khoản vào cuối tháng này."},
    "買掛金": {"example": "仕入先への買掛金は期日通りにしっかりと支払う。", "meaning": "Khoản chi chưa thanh toán của nhà thầu sẽ được thanh toán chặt chẽ đúng hạn."},
    "懇親会 /こんしんかい/": {"example": "新しい部署に配属されたため、部署の懇親会に参加した。", "meaning": "Vì tôi được phân công vào bộ phận mới nên đã tham gia bữa tiệc giao lưu của bộ phận."},
    "仕入れ": {"example": "新鮮な食材を朝市で直接仕入れている。", "meaning": "Nguyên liệu tươi sống được mua về (nhập kho) trực tiếp từ chợ sáng."},
    "軽自動車": {"example": "燃費の良さと小回りの良さで、営業用には軽自動車が最適だ。", "meaning": "Với mức tiết kiệm nhiên liệu tốt và tính xoay chuyển nhanh (đi qua ngõ hẹp tốt), xe ô tô hạng nhẹ rất phù hợp cho doanh nghiệp."},
    "手配": {"example": "会議の後は宴会があるため、レストランの手配をしておいてください。", "meaning": "Vì sau cuộc họp có buổi tiệc, xin hãy chuẩn bị / sắp xếp nhà hàng trước nhé."},
    "代行運転": {"example": "お酒を飲んだので、スマホアプリで代行運転を頼んだ。", "meaning": "Vì tôi đã uống rượu nên tôi đặt gọi dịch vụ lái xe hộ (thay thế) qua ứng dụng trên smartphone."},
    "シニア層": {"example": "現在、シニア層をターゲットにした健康商品が売れている。", "meaning": "Hiện nay, các sản phẩm sức khỏe nhắm mục tiêu vào tầng lớp người lớn tuổi bán rất chạy."},
    "本場": {"example": "その製品は、世界で最も技術が進んでいる本場から輸入しています。", "meaning": "Sản phẩm này được nhập khẩu từ trung tâm nơi xuất xứ nổi tiếng có công nghệ tiên tiến nhất thế giới."},
    "伸び率": {"example": "ベンチャー企業の利益の伸び率には目を見張るものがある。", "meaning": "Tỷ giá lợi nhuận tăng trưởng của công ty mạo hiểm thật đáng kinh ngạc."},
    "中間決算": {"example": "今年度の中間決算では、予想以上に利益が出た。", "meaning": "Trong báo cáo tài chính bán niên của năm nay, lợi nhuận đạt tới mức ngoài mong đợi."},
    "人件費": {"example": "業務のIT化を進め、人件費の削減を図る。", "meaning": "Chúng tôi đang đẩy mạnh công nghệ số vào công việc, và nhắm đến việc cắt giảm chi phí nhân sự."}
}

data.update(new_data)
with open('examples.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Second batch of generated examples appended. Total current:", len(data))
