import json

data = {
    "赤字補填": {"example": "赤字補填のために、役員報酬を削減した。", "meaning": "Đã cắt giảm thù lao của giám đốc để bù lỗ."},
    "撤収": {"example": "イベントが終わったので、すぐに機材を撤収してください。", "meaning": "Do sự kiện đã kết thúc, vui lòng dọn dẹp và thu dọn thiết bị ngay lập tức."},
    "撤退": {"example": "採算が合わないため、海外市場からの撤退を決定した。", "meaning": "Do không có lãi, chúng tôi quyết định rút lui khỏi thị trường nước ngoài."},
    "撤去": {"example": "古い設備を撤去して、新しい機械を導入する。", "meaning": "Tháo dỡ thiết bị cũ và giới thiệu máy móc mới."},
    "決算報告": {"example": "明日の午後に、株主向けの決算報告が行われます。", "meaning": "Vào chiều mai, báo cáo tài chính sẽ được thực hiện cho các cổ đông."},
    "社長補佐": {"example": "彼は長年、社長補佐として会社を支えてきました。", "meaning": "Ông ấy đã hỗ trợ công ty nhiều năm với tư cách là trợ lý giám đốc."},
    "非常に苦情を言う人": {"example": "クレーマーや非常に苦情を言う人には、冷静に対応する必要がある。", "meaning": "Cần phải ứng phó bình tĩnh đối với những người hayếu nại và người hay càu nhàu."},
    "契約締結": {"example": "ついに、大企業との契約締結に至りました。", "meaning": "Cuối cùng, chúng ta đã đạt được việc ký kết hợp đồng với công ty lớn."},
    "一本締め": {"example": "最後は、皆さんで一本締めをしてお開きにしましょう。", "meaning": "Cuối cùng, mọi người hãy vỗ tay một nhịp (一本締め) để kết thúc nhé."},
    "万歳三唱": {"example": "新社長の就任を祝して、万歳三唱を行った。", "meaning": "Mọi người đã hô vạn tuế 3 lần để chúc mừng tân giám đốc nhậm chức."},
    "ウェブ観覧": {"example": "業務時間中の私的なウェブ観覧は控えてください。", "meaning": "Vui lòng hạn chế lướt web cá nhân trong giờ làm việc."},
    "𠮟責": {"example": "ミスを隠したことで、上司から厳しく叱責された。", "meaning": "Vì che giấu lỗi, anh ấy đã bị cấp trên khiển trách nghiêm khắc."},
    "人事考課": {"example": "今年の人事考課は、実績に基づいて公平に評価されます。", "meaning": "Đánh giá hiệu suất nhân sự năm nay sẽ được đánh giá công bằng dựa trên thành tích."},
    "捺印": {"example": "書類の内容を確認し、署名と捺印をお願いします。", "meaning": "Vui lòng kiểm tra nội dung tài liệu và ký tên, đóng dấu."},
    "配付": {"example": "会議の前に、参加者へ資料を配付しておいてください。", "meaning": "Trước cuộc họp, hãy phân phát tài liệu cho những người tham gia."},
    "決裁": {"example": "この企画書は、すでに部長の決裁を頂いています。", "meaning": "Bản kế hoạch này đã nhận được sự phê duyệt của trưởng phòng."},
    "解体": {"example": "古い工場を解体し、新しい物流センターを建設する。", "meaning": "Tháo dỡ nhà máy cũ và xây dựng trung tâm logistics mới."},
    "積載": {"example": "トラックへの荷物の積載は、安全第一で行ってください。", "meaning": "Việc xếp hàng hóa lên xe tải, hãy ưu tiên an toàn lên hàng đầu."},
    "一存": {"example": "この件は、私の一存では決めかねます。", "meaning": "Vấn đề này, tôi không thể tự mình quyết định theo ý kiến cá nhân được."},
    "一両日": {"example": "結果につきましては、一両日中にご連絡いたします。", "meaning": "Về kết quả, chúng tôi sẽ liên hệ trong một hai ngày tới."},
    "一通り": {"example": "マニュアルの内容は、一通り目を通しておいてください。", "meaning": "Vui lòng đọc qua toàn bộ nội dung của sách hướng dẫn."},
    "名簿": {"example": "出席者の名簿を更新しておいてください。", "meaning": "Vui lòng cập nhật danh sách những người tham dự."},
    "免税店": {"example": "空港の免税店でお土産を購入した。", "meaning": "Tôi đã mua quà lưu niệm ở cửa hàng miễn thuế tại sân bay."},
    "折り返し": {"example": "担当者が戻り次第、折り返しお電話いたします。", "meaning": "Ngay khi người phụ trách quay lại, chúng tôi sẽ gọi lại cho bạn."},
    "患う": {"example": "彼は長年、重い病気を患っているそうです。", "meaning": "Nghe nói ông ấy đã mắc bệnh nặng nhiều năm."},
    "疎遠": {"example": "転職してからは、元同僚たちとも疎遠になってしまった。", "meaning": "Kể từ khi chuyển việc, tôi cũng dần xa cách với những đồng nghiệp cũ."},
    "社葬": {"example": "故人の功績を讃え、社葬が執り行われることになった。", "meaning": "Để ca ngợi công lao của ngươì đã khuất, tang lễ nội bộ công ty sẽ được tổ chức."},
    "香典": {"example": "葬儀には香典を持参するのが一般的なマナーです。", "meaning": "Mang theo tiền phúng viếng đến đám tang là phép lịch sự thông thường."},
    "供花": {"example": "取引先の社長が亡くなり、供花を手配した。", "meaning": "Giám đốc công ty đối tác qua đời, nên chúng tôi đã chuẩn bị vòng hoa viếng."},
    "3対2": {"example": "投票の結果、３対２で新プロジェクトが承認された。", "meaning": "Kết quả biểu quyết, dự án mới đã được phê duyệt với tỉ lệ 3 đối 2."},
    "参列": {"example": "社長の結婚式には、多くの社員が参列した。", "meaning": "Nhiều nhân viên đã đến tham dự lễ cưới của giám đốc."},
    "検品": {"example": "出荷前に、すべての商品の検品を行ってください。", "meaning": "Trước khi xuất hàng, vui lòng kiểm tra chất lượng tất cả các sản phẩm."},
    "代替品": {"example": "在庫が切れているため、代替品をご提案させていただきます。", "meaning": "Vì hết hàng, chúng tôi xin phép đề xuất một sản phẩm thay thế."},
    "長引く": {"example": "会議が長引いており、次の予定に遅れそうです。", "meaning": "Cuộc họp đang kéo dài, có vẻ sẽ bị trễ lịch trình tiếp theo."},
    "来期": {"example": "来期の売上目標は、今期比10％増とします。", "meaning": "Mục tiêu doanh số của kỳ tới sẽ là tăng 10% so với kỳ này."},
    "見込み": {"example": "来月には、黒字に転じる見込みです。", "meaning": "Dự kiến vào tháng tới, chúng ta sẽ chuyển sang có lãi."},
    "手直し": {"example": "提出されたレポートには、少し手直しが必要です。", "meaning": "Bản báo cáo được nộp cần phải chỉnh sửa một chút."},
    "隣り合わせ": {"example": "この業界は、常に大きなリスクと隣り合わせだ。", "meaning": "Ngành này luôn kề cận với những rủi ro lớn."},
    "決済": {"example": "オンラインショップでの決済方法はクレジットカードのみです。", "meaning": "Phương thức thanh toán trên cửa hàng trực tuyến chỉ là thẻ tín dụng."},
    "手形": {"example": "支払いは現金ではなく手形で受け取った。", "meaning": "Khoản thanh toán đã được nhận bằng hối phiếu thay vì tiền mặt."},
    "一括請求": {"example": "複数月の利用料金を、一括請求させていただきます。", "meaning": "Chúng tôi xin phép gộp hóa đơn thanh toán cho nhiều tháng sử dụng."},
    "約束手形": {"example": "期日に必ず支払うという約束手形を振り出した。", "meaning": "Đã phát hành một kỳ phiếu (hối phiếu nhận nợ) cam kết chắc chắn sẽ trả vào ngày đáo hạn."},
    "稟議書": {"example": "新しいパソコンを購入するため、稟議書を提出した。", "meaning": "Để mua máy tính mới, tôi đã nộp tờ trình xin đánh giá."},
    "始末書": {"example": "重大なミスを犯したため、始末書を書かされた。", "meaning": "Vì mắc lỗi nghiêm trọng, tôi đã bị bắt viết bản kiểm điểm."},
    "顛末書": {"example": "事故の原因と対策をまとめた顛末書を提出してください。", "meaning": "Vui lòng nộp báo cáo tường trình tóm tắt nguyên nhân và các biện pháp đối phó sự cố."},
    "話が通る": {"example": "彼に説明すれば、すぐに話が通るはずだ。", "meaning": "Nếu giải thích với anh ấy, chắc chắn câu chuyện sẽ được hiểu ngay lập tức."},
    "決裁印": {"example": "書類に部長の決裁印をもらってから、経理に提出してください。", "meaning": "Vui lòng lấy con dấu phê duyệt của trưởng phòng trên tài liệu, sau đó nộp cho phòng kế toán."},
    "仮免許書": {"example": "運転免許の仮免許書を取得しました。", "meaning": "Tôi đã lấy được giấy phép lái xe tạm thời."},
    "労災保険": {"example": "仕事中の怪我は、労災保険が適用されます。", "meaning": "Chấn thương trong công việc sẽ được áp dụng bảo hiểm tai nạn lao động."},
    "Day3": {"example": "Day3の内容は復習しておいてください。", "meaning": "Hãy ôn lại nội dung của Ngày 3."},
    "目が腫れるほど泣く": {"example": "失敗を悔やんで、彼女は目が腫れるほど泣いた。", "meaning": "Cô ấy đã khóc đến mức sưng cả mắt vì hối hận về thất bại."},
    "構図": {"example": "業界の競争構図が大きく変化している。", "meaning": "Bức tranh cạnh tranh của ngành đang thay đổi đáng kể."},
    "フル稼働": {"example": "年末の繁忙期は、工場が24時間フル稼働する。", "meaning": "Vào mùa bận rộn cuối năm, nhà máy sẽ hoạt động hết công suất 24/24."},
    "全力を挙げる": {"example": "会社再建のために、全社員が全力を挙げて取り組んでいる。", "meaning": "Để tái thiết công ty, tất cả nhân viên đang làm việc nỗ lực hết sức."},
    "見通し": {"example": "プロジェクトの完了見通しは立っていません。", "meaning": "Chưa có triển vọng hoàn thành dự án."},
    "直撃": {"example": "台風の直撃により、物流に大きな影響が出た。", "meaning": "Do bão đổ bộ trực tiếp nên hệ thống hậu cần bị ảnh hưởng nghiêm trọng."},
    "突発的": {"example": "突発的なトラブルが発生し、対応に追われている。", "meaning": "Sự cố đột xuất phát sinh nên chúng tôi đang bận rộn đối phó."},
    "減収": {"example": "昨年度は、コロナの影響で大幅な減収となった。", "meaning": "Năm ngoái, do ảnh hưởng của dịch Corona nên doanh thu giảm mạnh."},
    "節税": {"example": "合法的な節税対策を税理士に相談する。", "meaning": "Tôi thảo luận với nhà tư vấn thuế về các biện pháp tối ưu hóa thuế (tránh thuế) hợp pháp."},
    "満期": {"example": "定期預金が満期を迎えたので、解約するつもりだ。", "meaning": "Tiền gửi có kỳ hạn đã đến ngày đáo hạn, vì vậy tôi định sẽ hủy."},
    "退職金": {"example": "定年になり、会社から退職金が支給された。", "meaning": "Đến tuổi nghỉ hưu, tôi đã được công ty trả tiền trợ cấp thôi việc."},
    "潤沢な資金": {"example": "そのベンチャー企業は、潤沢な資金を背景に急成長している。", "meaning": "Công ty khởi nghiệp đó đang phát triển nhanh chóng với sự hỗ trợ của nguồn vốn dồi dào."},
    "投資ビザ": {"example": "日本で起業するため、投資ビザの取得を目指す。", "meaning": "Để khởi nghiệp ở Nhật, tôi đặt mục tiêu lấy được visa đầu tư."},
    "月一": {"example": "部内のミーティングは月一のペースで開催される。", "meaning": "Cuộc họp nội bộ được tổ chức với tốc độ mỗi tháng một lần."},
    "早出 /はやで/": {"example": "明日は会議の準備があるため、早出します。", "meaning": "Sáng mai tôi sẽ đi làm sớm vì phải chuẩn bị cho cuộc họp."},
    "支出を削る": {"example": "利益を出すためには、無駄な支出を削る必要がある。", "meaning": "Để tạo ra lợi nhuận, cần phải cắt giảm những chi tiêu lãng phí."},
    "ルールを破棄する": {"example": "時代に合わない古いルールを破棄し、新しい枠組みを作る。", "meaning": "Loại bỏ những quy tắc cũ lỗi thời và tạo ra một khuôn khổ mới."},
    "電話を寄越す /よこす/": {"example": "先方からクレームの電話を寄越してきた。", "meaning": "Đối tác đã gọi điện thoại than phiền đến."},
    "書庫 /しょこ/": {"example": "古い書類は地下の書庫に保管されています。", "meaning": "Các tài liệu cũ được lưu trữ trong kho lưu trữ tài liệu dưới tầng hầm."},
    "暫定的": {"example": "システム障害のため、暫定的な対応をとる。", "meaning": "Do lỗi hệ thống, chúng tôi sẽ thực hiện biện pháp ứng phó tạm thời."},
    "要請": {"example": "政府から外出自粛の要請が出された。", "meaning": "Chính phủ đã đưa ra yêu cầu hạn chế đi ra ngoài."},
    "収益": {"example": "新商品のヒットにより、大幅な収益増が見込める。", "meaning": "Nhờ sản phẩm mới bán chạy, dự kiến ​​tăng trưởng doanh thu đáng kể."},
    "出店": {"example": "来月、都心に新しい店舗を出店する予定だ。", "meaning": "Tháng tới, chúng tôi dự định mở một cửa hàng mới ở trung tâm thành phố."},
    "役員会": {"example": "明日の役員会で、重要な経営方針が決定される。", "meaning": "Tại cuộc họp hội đồng quản trị ngày mai, chính sách quản lý quan trọng sẽ được quyết định."},
    "方針=方策=政策": {"example": "会社は環境保護に取り組む方針を打ち出した。", "meaning": "Công ty đã đưa ra chính sách (phương pháp) nỗ lực bảo vệ môi trường."},
    "染みつく": {"example": "新入社員の頃からの習慣が、体に染みついている。", "meaning": "Thói quen từ những ngày mới vào công ty đã ăn sâu vào trong tôi."},
    "賞与": {"example": "業績が好調なため、夏の賞与が増額された。", "meaning": "Nhờ hiệu suất kinh doanh tốt, tiền thưởng mùa hè đã được tăng lên."},
    "入念": {"example": "プレゼンの前に、入念なリハーサルを行った。", "meaning": "Trước bài thuyết trình, tôi đã tiến hành diễn tập kỹ lưỡng."},
    "詰める": {"example": "細部の条件について、もう少し相手と詰める必要がある。", "meaning": "Về các điều kiện chi tiết, cần phải thảo luận đi sâu (bàn bạc cụ thể) thêm với đối tác."},
    "意識改革": {"example": "組織の風通しを良くするため、全社員の意識改革を促す。", "meaning": "Để tổ chức được minh bạch hơn, chúng tôi thúc đẩy việc cải cách ý thức của tất cả nhân viên."},
    "精算書": {"example": "出張から戻ったら、速やかに交通費の精算書を提出してください。", "meaning": "Sau khi trở về từ chuyến công tác, vui lòng nộp bản thanh toán tiền tàu xe ngay."},
    "浮かない顔": {"example": "彼は朝から浮かない顔をしているが、何かあったのだろうか。", "meaning": "Từ sáng anh ấy đã mang bộ mặt ủ rũ không vui, không biết đã có chuyện gì nhỉ?"},
    "打開策": {"example": "この困難な状況を乗り切るための打開策を考えなければならない。", "meaning": "Chúng ta phải suy nghĩ tìm ra giải pháp đột phá để vượt qua tình huống khó khăn này."},
    "相談料": {"example": "初回相談は無料ですが、２回目以降は相談料が発生します。", "meaning": "Lần tư vấn đầu tiên là miễn phí, nhưng từ lần thứ hai trở đi sẽ tốn phí tư vấn."},
    "冊子": {"example": "展示会で配布する会社案内の冊子を作成する。", "meaning": "Tạo cuốn sổ tay nhỏ hướng dẫn về công ty để phân phát tại triển lãm."},
    "整理整頓": {"example": "仕事の効率を上げるため、デスク周りの整理整頓を心がけましょう。", "meaning": "Để tăng hiệu quả công việc, hãy chú ý sắp xếp gọn gàng quanh bàn làm việc."},
    "株式相場": {"example": "昨今の株式相場は非常に不安定な動きを見せている。", "meaning": "Thị trường chứng khoán (giá cổ phiếu) dạo gần đây đang cho thấy những biến động rất không ổn định."},
    "同業他社": {"example": "我々は同業他社に負けない独自のサービスを提供する必要がある。", "meaning": "Chúng ta cần cung cấp những dịch vụ độc đáo không thua kém các công ty đối thủ cùng ngành."},
    "業績": {"example": "彼の努力のおかげで、営業部の業績が大きく向上した。", "meaning": "Nhờ sự nỗ lực của anh ấy, hiệu suất kinh doanh (thành tích) của phòng kinh doanh đã tăng lên đáng kể."},
    "委託手数料": {"example": "業務を外部に委託するため、委託手数料が発生する。", "meaning": "Do ủy quyền công việc cho bên ngoài, phí ủy thác sẽ phát sinh."},
    "投資信託": {"example": "老後の資金作りとして、投資信託を始めた。", "meaning": "Tôi đã bắt đầu mua quỹ tín thác đầu tư để tạo nguồn vốn cho tuổi già."},
    "コア収益": {"example": "当社のコア収益は、通信事業によって支えられている。", "meaning": "Cốt lõi doanh thu (nguồn lợi nhuận chính) của công ty chúng tôi được chống đỡ bởi mảng kinh doanh viễn thông."},
    "持続的発展": {"example": "企業が生き残るためには、持続的発展が不可欠だ。", "meaning": "Để doanh nghiệp tồn tại, sự phát triển bền vững là điều vô cùng cần thiết."},
    "生き残る": {"example": "激しい競争の中で生き残るための戦略を立てる。", "meaning": "Lập chiến lược để sống sót trong môi trường cạnh tranh khốc liệt."},
    "株を保有する": {"example": "彼はA社の株を大量に保有しており、大株主である。", "meaning": "Ông ấy nắm giữ số lượng lớn cổ phiếu của công ty A và là một cổ đông lớn."},
    "注意を促す": {"example": "セキュリティインシデントを防ぐため、全社員に注意を促すメールを送信した。", "meaning": "Để phòng ngừa sự cố bảo mật, tôi đã gửi email kêu gọi sự chú ý tới tất cả nhân viên."},
    "不況になる": {"example": "世界経済が不況になると、輸出産業は大きな打撃を受ける。", "meaning": "Nếu nền kinh tế thế giới rơi vào khủng hoảng, ngành xuất khẩu sẽ chịu tổn thất lớn."},
    "上期": {"example": "上期の売上目標は、前年同期比10%増に設定された。", "meaning": "Mục tiêu doanh số của nửa đầu năm được thiết lập tăng 10% so với cùng kỳ năm ngoái."},
    "下期": {"example": "下期には新製品の発売が控えており、売上の増加が期待される。", "meaning": "Vào nửa cuối năm, việc phát hành sản phẩm mới đang đến gần, hy vọng doanh thu sẽ tăng."},
    "一元化": {"example": "各部署の顧客データを一元化し、マーケティング活動を効率化する。", "meaning": "Tập trung (thống nhất một mối) dữ liệu khách hàng của các bộ phận để tối ưu hóa hoạt động marketing."},
    "レントゲン": {"example": "健康診断で胸部のレントゲン撮影を行った。", "meaning": "Tôi đã chụp X-quang phần ngực trong đợt khám sức khỏe."},
    "キーパーソン": {"example": "このプロジェクトを成功させるには、彼がキーパーソンとなる。", "meaning": "Để thành công dự án này, anh ấy sẽ là nhân vật chủ chốt (key person)."},
    "シュレッダー": {"example": "機密文書は必ずシュレッダーにかけて破棄してください。", "meaning": "Các tài liệu mật nhất định phải được cắt (xé nhỏ) bằng máy hủy tài liệu rồi mới vứt bỏ."},
    "ファイリング": {"example": "後ですぐ取り出せるように、資料を件名ごとにファイリングする。", "meaning": "Phân loại lưu trữ tài liệu theo từng chủ đề để sau này có thể dễ dàng lấy ra."},
    "アレンジ": {"example": "既存のデザインを少しアレンジして、新しいパンフレットを作成した。", "meaning": "Thay đổi sắp xếp (điều chỉnh) lại thiết kế cũ bản một chút để tạo ra ấn phẩm quảng cáo mới."},
    "気を遣う": {"example": "取引先の社長との会食では、何かと気を遣うことが多い。", "meaning": "Trong bữa ăn tối với giám đốc bên đối tác, có rất nhiều chuyện cần phải lưu tâm giữ ý tứ (để ý đến cảm xúc)."},
    "販売戦略": {"example": "ターゲット層を見直し、新たな販売戦略を立案する。", "meaning": "Đánh giá lại đối tượng khách hàng mục tiêu và lập chiến lược bán hàng mới."},
    "コンピューターを立ち上げる": {"example": "出社したら、まずコンピューターを立ち上げてメールをチェックする。", "meaning": "Sau khi đến công ty làm, trước tiên tôi khởi động máy tính và kiểm tra email."},
    "鶴の一声": {"example": "会議が紛糾したが、社長の鶴の一声で結論が出た。", "meaning": "Cuộc họp đã xảy ra những ý kiến hỗn loạn nhưng kết luận đã được đưa ra chỉ bởi một tiếng nói có trọng lượng của giám đốc."},
    "採算が取れない": {"example": "この商品は製造コストが高く、売っても採算が取れない。", "meaning": "Sản phẩm này chi phí sản xuất cao, dù có bán cũng không thu đủ lợi nhuận (bù đắp chi phí)."},
    "24時間稼働": {"example": "当社のサーバーはトラブル防止のため、24時間稼働しています。", "meaning": "Máy chủ của công ty chúng tôi hoạt động 24/24 để phòng ngừa sự cố."},
    "思いもしなかった": {"example": "この企画がこんな大ヒットになるとは思いもしなかった。", "meaning": "Không ngờ (đã chưa từng nghĩ đến) rằng kế hoạch này lại trở thành một cú hit lớn như vậy."},
    "辞表": {"example": "独立して起業するため、ついに会社へ辞表を提出した。", "meaning": "Để tự kinh doanh khởi nghiệp, cuối cùng tôi đã nộp đơn từ chức lên công ty."},
    "そこを何とか": {"example": "「そこを何とか期限を延長していただけませんか」と頼み込んだ。", "meaning": "Tôi đã nài nỉ cầu xin: 'Anh/chị có thể vui lòng xoay sở xem xét gia hạn thêm thời gian về điểm đó được không?'."},
    "無理は承知の上で": {"example": "無理は承知の上で、あえてこの提案をさせていただきます。", "meaning": "Dù biết là quá sức (vô lý), nhưng tôi xin phép được mạnh dạn đưa ra đề xuất này."},
    "契約が成立しました": {"example": "長年の交渉の末、ようやく契約が成立しました。", "meaning": "Sau nhiều năm đàm phán, cuối cùng hợp đồng cũng đã được thành lập (ký kết)."}
}

with open('examples.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("First batch of generated examples saved.")
